
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:3000"
    container_name: solar-fin-app
    env_file:
      - .env
    environment:
      - DATABASE_MODE=postgres
      - DATABASE_URL=postgresql://solaruser:solarpass@db:5432/solar_fin_db
      # JWT_SECRET should be defined in your .env file
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: solar-fin-db
    environment:
      POSTGRES_USER: solaruser
      POSTGRES_PASSWORD: solarpass
      POSTGRES_DB: solar_fin_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432" # Porta externa alterada para 5433
    restart: unless-stopped

# To run: docker-compose up --build
# To stop: docker-compose down
# Note: The first time you run 'docker-compose up', the init.sql script will execute.
# If you modify init.sql later, you may need to remove the 'pgdata' volume 
# (e.g., 'docker-compose down -v' and then 'docker-compose up --build') for the script to re-run.
# Ensure your .env file contains the JWT_SECRET.
# Ensure 'sql/init.sql' exists in your project root and contains the correct DDL for your tables.
